Repository Jacinth-Mahanta/CalculatorApp, pull requests merged in 2023-10, with the labels that each got.

#6 AC button feature added.
  .idea/compiler.xml
  .idea/misc.xml
  app/src/main/java/com/jacinthmahanta/calculator/Calculator.kt
  app/src/main/res/values/themes.xml
Labels: hactoberfest-accepted

#5 impl viewbinding, optimised code
  .idea/.name
  .idea/gradle.xml
  .idea/kotlinc.xml
  app/build.gradle
  app/src/main/java/com/jacinthmahanta/calculator/Calculator.kt
Labels: hacktoberfest

#9 disable dark mode + set status bar color transparent
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/themes.xml
Labels: hacktoberfest

#13 Feature/clear history functionality
  .idea/discord.xml
  .idea/misc.xml
  app/src/main/java/com/jacinthmahanta/calculator/Calculator.kt
  app/src/main/java/com/jacinthmahanta/calculator/HistoryAdapter.kt
  app/src/main/res/drawable/closebutton.xml
  app/src/main/res/drawable/historybutton.xml
  app/src/main/res/layout/activity_calculator.xml
  app/src/main/res/layout/row_history.xml
Labels: hacktoberfest-accepted

#17 Solve Zero Division Crash issue
  .idea/kotlinc.xml
  .idea/misc.xml
  app/src/main/java/com/jacinthmahanta/calculator/Calculator.kt
Labels: hacktoberfest-accepted
